#!/bin/sh

# TX config
export TX_IP='192.168.1.2'
export TX_ROUTER_IP='192.168.50.1'  # Router receiving ping
export PKT_TIME=0.05  # Interval between pings in seconds (20 pings/s)

# Default ASUS router IP address
export IP_ADDR='192.168.50.1'

# Experiment config
export EXP_NAME='test_tp'
export CH_NO=1
export BW=20
export IF='eth5'  # eth5 for 2GHz, eth6 for 5GHz
export MAC_ADDR='d8:3a:dd:a4:0a:d1'

# Duration of collection (ignored for streaming, kept for reference)
export DURATION=60

# Array of APs used in experiment
export AP_NO=0

# Coordinates and orientation of AP 0
export AP_0_X=0.0
export AP_0_Y=0.5
export AP_0_THETA=0
